pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out source code...'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'docker run --rm -v "$PWD/app:/app" -w /app node:22-alpine npm ci'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t devops-cicd-platform:1.0 -f docker/Dockerfile .'
            }
        }
    }
}