pipeline {
    agent any
    environment {
      IMAGE_TAG = "${env.BUILD_NUMBER}"
  }
    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out source code...'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                docker run --rm \
                  -v /home/jay/jenkins_home/workspace/devops-cicd-platform/app:/app \
                  -w /app \
                  node:22-alpine \
                  sh -c "ls -la && npm ci"
                '''
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t devops-cicd-platform:${IMAGE_TAG} -f docker/Dockerfile .'
            }
        }
        
        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-credentials',
                    usernameVariable: 'DOCKERHUB_USER',
                    passwordVariable: 'DOCKERHUB_PASS'
                )]) {
                    sh 'echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin'
                }
            }
        }
        stage('Docker Tag') {
            steps {
                sh 'docker tag devops-cicd-platform:${IMAGE_TAG} mrityunjaybhagat/devops-cicd-platform:${IMAGE_TAG}'
            }
        }
        stage('Docker Push') {
            steps {
                sh 'docker push mrityunjaybhagat/devops-cicd-platform:${IMAGE_TAG}'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                helm upgrade --install devops-cicd-platform helm/devops-cicd-platform \
                  --set image.tag=${IMAGE_TAG}
                '''
            }
        }
        
        
        
    }
}
