apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-cicd-platform
  labels:
    app: devops-cicd-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-cicd-platform
  template:
    metadata:
      labels:
        app: devops-cicd-platform
    spec:
      containers:
        - name: devops-cicd-platform
          image: mrityunjaybhagat/devops-cicd-platform:1.0
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
